### ISSUE TITLE
Why CI is failing

### ISSUE THREAD

**Issue by gotmax23** [robertdebock/ansible-collection-roles#2]
Hi Robert,

> ERROR! Galaxy import process failed: 'requires_ansible' in meta/runtime.yml is mandatory, but no meta/runtime.yml found (Code: None)

\- https://github.com/robertdebock/ansible-collection-roles/actions/runs/1204982715

You need to create a `meta/runtime.yml` file with contents like this:

``` yaml
---
requires_ansible: '>=2.9.10'
```

Thanks,
Maxwell

**Comment by robertdebock** [comment]
@gotmax23, we should collaborate at some point, it would be great to meet you in person, but I'm not sure where you are located. (Me in .nl)

**Comment by robertdebock** [comment]
There is another failure, I've [requested some help](https://github.com/ansible/galaxy/issues/2790).

**Comment by gotmax23** [comment]
> There is another failure, I've [requested some help](https://github.com/ansible/galaxy/issues/2790).

Maybe it has something to do with this `2`, which makes that file invalid yaml.

https://github.com/robertdebock/ansible-collection-roles/blob/14772d4780c71020e864512ab609c489d2695db9/roles/alternatives/meta/main.yml#L1
