### ISSUE TITLE
Question regarding SSH role

### ISSUE THREAD

**Issue by flotho** [robertdebock/ansible-collection-roles#5]
Hi,

Thanks for the amazing collection your proposed here.
I have a question reagrding the role openssh and the include directive.
I'm currently running your role on a rocky linux 9 and a subdirectory exists with this directive ```Include /etc/ssh/sshd_config.d/*.conf```
In the subfolder some redhat specific files are existing (sshd_config.d/50-redhat.conf) : 
```
# This system is following system-wide crypto policy. The changes to
# crypto properties (Ciphers, MACs, ...) will not have any effect in
# this or following included files. To override some configuration option,
# write it before this block or include it before this file.
# Please, see manual pages for update-crypto-policies(8) and sshd_config(5).
Include /etc/crypto-policies/back-ends/opensshserver.config

SyslogFacility AUTHPRIV

ChallengeResponseAuthentication no

GSSAPIAuthentication yes
GSSAPICleanupCredentials no

UsePAM yes

X11Forwarding yes

# It is recommended to use pam_motd in /etc/pam.d/sshd instead of PrintMotd,
# as it is more configurable and versatile than the built-in version.
PrintMotd no

```

What is your recommendation to be able to handle this, change the role or change the optins to reflect the content of this file?
Thanks for your help.

**Comment by robertdebock** [comment]
If you would like to modify any of the parameters, try to set Ansible variables. If the values in `/etc/ssh/sshd_config.d//50-redhat.conf` are okay, you can leave that as is.
