### ISSUE TITLE
Using your roles or the collection of roles?

### ISSUE THREAD

**Issue by bitfoo1** [robertdebock/ansible-collection-roles#8]
Hi,

thank you for your roles. I am considering using allot of them to provision my servers. But I am quite unsure if I should use your roles or this collection? Which one will be mit up-to-date? Or are they stay the same?

Thank you in advance
Daniel

**Comment by ricariel** [comment]
This collection is nearly up to date here in GitHub but not in galaxy sadly.

**Comment by chris968** [comment]
It's seems there is a version miss-match with Ansible Galaxy since a long time now, I previously used a fixed version from the git repository but they have now disappear, I have to use the commit hash ...

**Comment by robertdebock** [comment]
Thanks, I fixed that uploading.

In general; I'm using the roles rather than the collection. The collection is such a big blob, updates would impact many roles...
